server:
  port: 8070
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs  # Path for the OpenAPI documentation
  swagger-ui:
    enabled: true
    path: /swagger-ui.html  # Path for the Swagger UI

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatdb
  config:
    additional-location : ../../../config/global/
  r2dbc:
    url: r2dbc:mysql://192.168.0.79:3306/platform
    host: 192.168.0.79
    port: 3306
    database: platform
    username: platform
    password: allofhealth!234
    driver: mysql
    pool:
      enabled: true
  sql:
    init:
      platform: mysql
logging:
  level:
#    root: TRACE         # Sets the default log level for all loggers
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    javax.management: TRACE
    io.asyncer: TRACE
    io.asyncer.r2dbc.mysql.client: OFF
    io.netty.resolver: TRACE
    reactor.netty: TRACE
    org.mongodb.driver: TRACE
    org.mongodb.driver.protocol.command: OFF
