server:
  port: 8070
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatdb
  config:
    additional-location : ../../../config/global/
  r2dbc:
    url: r2dbc:mysql://192.168.0.2:3306/platform
    host: 192.168.0.2
    port: 3306
    database: platform
    username: platform
    password: allofhealth!234
    driver: mysql
    pool:
      enabled: true
  sql:
    init:
      platform: mysql
logging:
  level:
    root: TRACE         # Sets the default log level for all loggers
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    javax.management: TRACE
    io.asyncer: TRACE
    io.asyncer.r2dbc.mysql.client: OFF
    io.netty.resolver: TRACE
    reactor.netty: TRACE
#  security:
#    oauth2:
#      client:
#        registration:
#          allofhealth_platform:
#            client-id: 76716d91-5c8d-44a9-93c6-ca7cd3a1d0f4
#            client-name: messenger
#            client-secret: